# Generated by Django 4.2.5 on 2023-09-25 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_and_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='view_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
